name: GhostChat
options:
  bundleIdPrefix: xyz.gbskgs
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  WebRTC:
    url: https://github.com/stasel/WebRTC.git
    from: "125.0.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_FILE: GhostChat/Resources/Info.plist

targets:
  GhostChat:
    type: application
    platform: iOS
    sources:
      - GhostChat
    dependencies:
      - package: WebRTC
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ivanpokhvalitov.ghostchat
        PRODUCT_NAME: "Ghost chat"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "3"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
    postCompileScripts: []

  GhostChatTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - GhostChatTests
    dependencies:
      - target: GhostChat
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ivanpokhvalitov.ghostchat.tests
